# Generated by Django 3.2.17 on 2023-09-27 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('document_type', models.CharField(choices=[('cc', 'Citizenship card'), ('ti', ' Identity card'), ('ce', 'Foreigner identification card')], max_length=4)),
                ('document_number', models.TextField(default='')),
            ],
            options={
                'db_table': 'unal_student',
                'unique_together': {('document_type', 'document_number')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('required_subjects', models.ManyToManyField(help_text='Save the subjects that must be approved by the student in order to enroll in this subject', to='grade_scoring.Subject')),
            ],
            options={
                'db_table': 'unal_subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('passed', models.BooleanField(default=False, help_text='Indicates whether the student passed the subject')),
                ('score', models.FloatField(blank=True, default=None, help_text='Indicates the current score', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_scoring.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_scoring.subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subjectstudent',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='student_and_subject_unique_together'),
        ),
    ]
